DROP TABLE IF EXISTS FOOTER;
CREATE TABLE FOOTER 
(
	id 			INT PRIMARY KEY,
	car 		VARCHAR(20), 
	length 		INT, 
	width 		INT, 
	height 		INT
);

INSERT INTO FOOTER VALUES (1, 'Hyundai Tucson', 15, 6, NULL);
INSERT INTO FOOTER VALUES (2, NULL, NULL, NULL, 20);
INSERT INTO FOOTER VALUES (3, NULL, 12, 8, 15);
INSERT INTO FOOTER VALUES (4, 'Toyota Rav4', NULL, 15, NULL);
INSERT INTO FOOTER VALUES (5, 'Kia Sportage', NULL, NULL, 18); 

SELECT * FROM FOOTER;




SELECT *
FROM
(SELECT TOP 1 car FROM footer WHERE car IS NOT NULL ORDER BY id DESC) car
CROSS JOIN
(SELECT TOP 1 length FROM footer WHERE length IS NOT NULL ORDER BY id DESC) length
CROSS JOIN
(SELECT TOP 1 width FROM footer WHERE width IS NOT NULL ORDER BY id DESC) width
CROSS JOIN
(SELECT TOP 1 height FROM footer WHERE height IS NOT NULL ORDER BY id DESC) height;